name: Tests Gibhub Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with: 
          node-version: '17.X'

      - name: Install dependencies
        run: yarn install
      
      - name: Test
        run: yarn testUnit